### ISSUE TITLE
Option in structures to specify "repeating script"

### ISSUE THREAD

**Issue by dfsek** [PolyhedralDev/Terra#111]
Add a `repeat` option to structure configs, which would have `min-duration`, `max-duration`, and `script` sub-keys. The specified script would then be repeated in an interval from `min-duration` to `max-duration`.

Example config:
```yml
repeat:
  min-duration: PT1M # 1 minute.
  max-duration: PT2M # 2 minutes.
  script: spawn_guardians
```
This config would run the `spawn_guardians` script every 1-2 minutes. It could be used to respawn guardians in an ocean monument structure.

The repeated script would be run at the structure's origin, and would only run when the origin is in a loaded chunk.
