### ISSUE TITLE
Fractal samplers incorrectly set seed of input sampler

### ISSUE THREAD

**Issue by Astrashh** [PolyhedralDev/Terra#147]
The following noise config produces a constant*, meaning the `func1` and `func2` are identical:
```yaml
type: Expression
equation: "func1(x, z) - func2(x, z)"
functions:
  func1:
    type: FBm
    octaves: 1
    function:
      type: Cellular
      salt: 1
  func2:
    type: FBm
    octaves: 1
    function:
      type: Cellular
      salt: 2
```

When commenting out the fractal sampler, it produces noise like so:
![image](https://user-images.githubusercontent.com/73215501/116779924-7e089f80-aabc-11eb-922f-7bd833a338ea.png)
