### ISSUE TITLE
frquency typo in default pack.yml

### ISSUE THREAD

**Issue by IamMusavaRibica** [PolyhedralDev/Terra#196]
There is a typo where it says frquency instead of frequency in noise.desert
```yaml
desert:
    type: DomainWarp
    dimensions: 2
    amplitude: 25
    function:
      type: Cellular
      frequency: 0.015
      return: Distance
    warp:
      **frquency**: 0.015
      type: OpenSimplex2
```
