### ISSUE TITLE
Biome blending options not working correctly

### ISSUE THREAD

**Issue by dav1d-pt** [PolyhedralDev/Terra#270]
## Pre-Issue Checklist

- [x] I have checked that I am on the latest version of Terra.
- [x] I have searched the github issue tracker for similar issues, including closed ones.
- [x] I have made sure that this is not a bug with another mod or plugin, and it is Terra that is causing the issue.
- [x] I have checked that this is an issue with Terra and not an issue with the pack I am using.
- [x] I have filled out and provided all the appropriate information.

## Environment

Name | Value
------ | ------
Terra Version | 5.4.1 BETA
Platform/Platform Version | Paper
Any External Plugins or Mods | None
Terra Packs In Use | My own
Terra Addons In Use | None

## Issue Description

When I set biome blending options that are higher than default ones, e.g. distance: 6, step: 6, then "spikes" appear at the border of the biome. It must also be a high y position of blocks in biome, e.g. 130+ (comparing to the rest of biomes that have y pos at 64).

This is an example biome config which is causing the problem:

``` yaml
id: MOUNTAINS
vanilla: MOUNTAINS
noise-equation: "-((y / base) ^ 2) + 1 + |noise2(x / 15, z / 15)| / 3 + |noise2(x / 34, z / 34)| / 3 + |noise2(x / 2, z / 2)| / 3"

variables:
  base: 130

blend:
  distance: 7
  step: 12

palette:
  - GRASSY: 255
```

![obraz](https://user-images.githubusercontent.com/24868270/135175561-a75f1d64-75df-4963-aba5-00ac12dc65a8.png)
