### ISSUE TITLE
[Feature] Structure modification config type

### ISSUE THREAD

**Issue by Astrashh** [PolyhedralDev/Terra#282]
## Feature Description

A new config type with the purpose of applying some kind of modification to a structure, and registering that modified structure as a new one.

An example config might look like this:

```yaml
id: TREES_THAT_ONLY_REPLACES_AIR_THAT_ALSO_HAS_DIAMOND_LEAVES
type: STRUCTURE_MOD

structures:
  - tree1: 1
  - tree2: 1
replaceable:
  - minecraft:air
replace:
  - from:
      - minecraft:oak_leaves
    to: 
      - minecraft:diamond_block: 1
      - minecraft:diamond_ore: 1
    noise:
      dimensions: 3
      type: WHITE_NOISE
```

### What Problem Does This Solve?

This solves the issue where you'd want to create multiple variations of a structure with just changed blocks, or some other kind of modification.

This would be especially useful for static schematic based structures, where things like procedural block variations can be introduced via replacement, or the ability to mask schematics via `replaceable`.

### Alternative Solutions

Currently you can create variants by duplicating structures (scripts, schematics, etc), however things like procedural block variations with static schematics isn't currently possible.
