### ISSUE TITLE
Fleshed out slope conditionals for palettes

### ISSUE THREAD

**Issue by Astrashh** [PolyhedralDev/Terra#52]
Add options to define palettes that are constrained to a range of slopes.

For example, if I wanted different palettes based on the inclination of terrain, I could define palette A for super steep areas, and palette B for very flat areas - which would be overlaid on the palettes already defined for the biome. Would also take absolute height into consideration. Perhaps this could be merged into the palette configuration, so that you don't have to define multiple palettes for each combination of height and slope.

A proposed palette configuration system including slope support:

```yaml
palette:
  "BLOCK:minecraft:bedrock": #palettes at start would take priority over ones defined below it
    height:
    - max: 1 #only max is defined so min would default to min world height
  bedrock_2:
    height:
    - max: 5 #same here, note bedrock_1 & 2 would overlap so 1 takes priority since its higher
  striped:
    height:
    - min: 50 #this palette would stripe between y50 and y60
      max: 52
    - min: 54
      max: 56
    - min: 58
      max: 60
  slope_striped:
    height:
    - min: 50
      max: 52
    - min: 54
      max: 56
    - min: 58
      max: 60
    slope:
    - min: 5
      max: 255
  grassy:
    height:
    - min: 60
      max: 200
    slope:
    - min: 0,
      max: 1.5
  rock: #palettes with no options would just mean it spawns under every condition - since this is at the bottom, anywhere without a palette will default to rock
```

It would be less simple to configure (not by much) but more powerful compared to the current method
The current MOUNTAINS_PRETTY palette config converted to this proposed system would look like:
```yaml
palette:
  "BLOCK:minecraft:bedrock":
    height:
    - max: 0
  BEDROCK_MOST:
    height:
    - max: 1
  BEDROCK_HALF:
    height:
    - max: 2
  BEDROCK_LITTLE:
    height:
    - max: 3
  RIVER_BOTTOM:
    height:
    - max: 61
  RIVER_SHORE:
    height:
    - max: 62
  MOUNTAIN_PRETTY:
    height:
    - max: 255
```
