### ISSUE TITLE
List of slant configs

### ISSUE THREAD

**Issue by Astrashh** [PolyhedralDev/Terra#91]
Sort of a duplicate of #52 but rather than re-doing how slopes and palettes are handled, just allow different sets of palettes to be defined at different slants.

###### Example
```yaml
slant:
  - threshold: 2
    palette:
      - "..." # Areas where: {2 > gradient > 9}
      - "..."
      - "..."
  - threshold: 9
    palette:
      - "..." # Areas where {gradient > 9}
      - "..."
      - "..."
```
