### ISSUE TITLE
"adjacent" feature to flora

### ISSUE THREAD

**Issue by Daxxas** [PolyhedralDev/Terra#97]
Recently I was trying to add vines to the crag biome, and doing it with flora was the logical way but it had a minor issue that made it a bit infuriating, the vines weren't going up to the very top of the moutains like so : 
![alt text](https://media.discordapp.net/attachments/765260067812540416/822956977133977610/unknown.png?width=959&height=602 "Logo Title Text 1")

and I had to make a terrascript to have the wines that I wanted, but it could be still possible to do with flora with a little adjustement

### The feature
it would a path in the flora config `adjacent:` that could look like so

```
adjacent:
  - top:
    - "minecraft:stone"
  - left:
    - "minecraft:sand"
   ...
```
it would spawn blocks next to where the flora is supposed to be spawned (and would only replace air ?)

maybe having something more flexible like : 
```
adjacent:
  - 0, 0, 1:
    - "minecraft:stone"
  - 1, 0, 0:
    - "minecraft:sand"
   ...
```

where `1, 0, 0:` would be the offset from the initial position

Thanks you for reading, I hope that my explanations are clear enough :)

**Comment by dfsek** [comment]
Flora objects are, per our definition, vertical only. If you want to place blocks adjacent to flora, use scripts. Your description of what you want "adjacent" to do was very cryptic, but it *sounds* like you want it to place blocks around the flora object, but correct me if I'm wrong.

Plus, would this not do what you want?
```yml
ceiling: true
search: DOWN
max-placements: 1
spawnable:
  - "minecraft:air"
replaceable:
  - "minecraft:air"
rotatable:
  - "minecraft:stone"
  - "minecraft:cobblestone"
  - "minecraft:mossy_cobblestone"
irrigable-offset: -1
irrigable:
  - "minecraft:stone"
  - "minecraft:cobblestone"
  - "minecraft:mossy_cobblestone"
```
